# Generated by Django 2.2.8 on 2022-11-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImg',
            new_name='TurfGallery',
        ),
    ]
