# Generated by Django 2.2.8 on 2022-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20221109_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfgallery',
            name='isheader',
            field=models.ImageField(null=True, upload_to='isheader/isheader'),
        ),
    ]
