# Generated by Django 2.2.8 on 2022-11-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_turfgallery_isheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turfgallery',
            options={'ordering': ['id']},
        ),
    ]
