# Generated by Django 2.2.8 on 2022-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20221111_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfgallery',
            name='isheader',
            field=models.BooleanField(default=False),
        ),
    ]
