# Generated by Django 2.2.8 on 2022-11-18 03:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
