# Generated by Django 2.2.8 on 2022-11-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('image', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
                ('username', models.TextField(max_length=100)),
                ('product_id', models.TextField()),
                ('product_name', models.TextField(max_length=100)),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
                ('image', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100)),
                ('price', models.FloatField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
