# Generated by Django 2.2.8 on 2022-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
