# Generated by Django 2.2.8 on 2022-11-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20221109_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsmodel',
            options={},
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
