# Generated by Django 2.2.8 on 2022-11-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_auto_20221111_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('firstname', models.TextField()),
                ('contactnumber', models.BigIntegerField()),
                ('houseno', models.TextField(default=0.0)),
                ('landmark', models.TextField()),
                ('location', models.TextField(max_length=100)),
                ('state', models.TextField(blank=True, null=True)),
                ('pincode', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='status',
            field=models.TextField(blank=True, default='Awaiting Fulfillment'),
        ),
    ]
