# Generated by Django 2.2.8 on 2022-11-09 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 12, 36, 32, 644381), max_length=30)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 12, 36, 32, 644423), max_length=30)),
                ('locality', models.CharField(max_length=30, null=True)),
                ('creator', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=30)),
                ('slots', models.IntegerField(default=2)),
                ('slot_available', models.IntegerField(default=1)),
                ('cron', models.IntegerField(default=1, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CategoriesModel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 12, 36, 32, 645370), max_length=30)),
                ('end_time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 9, 12, 36, 32, 645384), max_length=30)),
                ('locality', models.CharField(max_length=30, null=True)),
                ('creator', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='Upcoming', max_length=30)),
                ('teams', models.IntegerField(default=1)),
                ('team_space_available', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('phoneno', models.CharField(default=7414414141, max_length=16)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True, default='12:36:32')),
                ('end_time', models.TimeField(blank=True, default='12:36:32')),
                ('locality', models.CharField(max_length=30, null=True)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.TournamentModel')),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phoneno', models.CharField(default=7414414141, max_length=16)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True, default='12:36:32')),
                ('end_time', models.TimeField(blank=True, default='12:36:32')),
                ('locality', models.CharField(max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.CategoriesModel')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.MatchModel')),
            ],
        ),
    ]
