# Generated by Django 2.2.8 on 2022-11-16 08:50

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0023_auto_20221116_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('subcountry', models.CharField(max_length=100, null=True)),
                ('geonameid', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 14, 20, 53, 816920), max_length=30),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='locality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 14, 20, 53, 816901), max_length=30),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:20:53'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='locality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:20:53'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 14, 20, 53, 818047), max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 16, 14, 20, 53, 818027), max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentrequestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='14:20:53'),
        ),
        migrations.AlterField(
            model_name='tournamentrequestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='14:20:53'),
        ),
        migrations.CreateModel(
            name='TurfCommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('likes_count', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 16, 14, 20, 53, 819677), max_length=30)),
                ('liked_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
