# Generated by Django 2.2.8 on 2022-11-22 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0051_auto_20221121_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_usModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('hidden', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameField(
            model_name='createteammodel',
            old_name='team_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tournamentmodel',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='tournamentrequestmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tournamentrequestmodel',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 11, 15, 41, 944474), max_length=30),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 11, 15, 41, 944454), max_length=30),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='11:15:41'),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='11:15:41'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 11, 15, 41, 945498), max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/team'),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 22, 11, 15, 41, 945484), max_length=30),
        ),
        migrations.AlterField(
            model_name='tournamentrequestmodel',
            name='end_time',
            field=models.TimeField(blank=True, default='11:15:41'),
        ),
        migrations.AlterField(
            model_name='tournamentrequestmodel',
            name='start_time',
            field=models.TimeField(blank=True, default='11:15:41'),
        ),
        migrations.AlterField(
            model_name='turfcommentsmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 11, 15, 41, 946785), max_length=30),
        ),
    ]
